fix wtforms Optional
The error was:

    TypeError: <class 'wtforms.validators.Optional'> is not a valid validator because it is a class, it should be an instance